### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by hawkinsp** [google-deepmind/tree#109]
Python 3.12 is the current stable release: dm-tree should release wheels for it.

**Comment by vvstubbs** [comment]
So is this the reason I can not install (or build from source for tat matter) dm-tree, required for building tensorflow for python 3.12. The error I get is:

`Traceback (most recent call last):
File "/home/vstubbs/Downloads/tmp/tree/setup.py", line 124, in <module>
setuptools.setup(
File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 107, in setup
return distutils.core.setup(**attrs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
return run_commands(dist)
^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
dist.run_commands()
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
self.run_command(cmd)
File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 1244, in run_command
super().run_command(command)
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/usr/lib/python3.12/site-packages/setuptools/command/install.py", line 86, in run
self.do_egg_install()
File "/usr/lib/python3.12/site-packages/setuptools/command/install.py", line 135, in do_egg_install
self.run_command('bdist_egg')
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 1244, in run_command
super().run_command(command)
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/usr/lib/python3.12/site-packages/setuptools/command/bdist_egg.py", line 164, in run
cmd = self.call_command('install_lib', warn_dir=0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
self.run_command(cmdname)
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 1244, in run_command
super().run_command(command)
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/usr/lib/python3.12/site-packages/setuptools/command/install_lib.py", line 11, in run
self.build()
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
self.run_command('build_ext')
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 1244, in run_command
super().run_command(command)
File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/home/vstubbs/Downloads/tmp/tree/setup.py", line 72, in run
self.build_extension(ext)
File "/home/vstubbs/Downloads/tmp/tree/setup.py", line 110, in build_extension
subprocess.check_call(
File "/usr/lib64/python3.12/subprocess.py", line 413, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j8', '--config', 'Release']' returned non-zero exit status 2.`

**Comment by SamuelMarks** [comment]
Same error occurring for me.

**Comment by cool-RR** [comment]
I am also affected by this. I can't upgrade my research environment to Python 3.12 because it depends on `dm-tree`.
